import { Layout, DashboardLayout } from "@blubberfish/lib-nebula/dashboard";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lilypad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Layout>
          <DashboardLayout>{children}</DashboardLayout>
        </Layout>
      </body>
    </html>
  );
}
